# coding: utf-8

require "terms_of_service_001"
require "privacy_policy_001"

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
ActiveRecord::Base.connection.execute("TRUNCATE sexes")
ActiveRecord::Base.connection.reset_pk_sequence!("sexes")
Sex.create(name: "男性", deleted: false)
Sex.create(name: "女性", deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE sexes")

ActiveRecord::Base.connection.execute("TRUNCATE countries")
ActiveRecord::Base.connection.reset_pk_sequence!("countries")
Country.create(name: "アイスランド", deleted: false)
Country.create(name: "アイルランド", deleted: false)
Country.create(name: "アゼルバイジャン", deleted: false)
Country.create(name: "アフガニスタン", deleted: false)
Country.create(name: "アブハジア", deleted: false)
Country.create(name: "アメリカ合衆国", deleted: false)
Country.create(name: "アラブ首長国連邦", deleted: false)
Country.create(name: "アルジェリア", deleted: false)
Country.create(name: "アルゼンチン", deleted: false)
Country.create(name: "アルバニア", deleted: false)
Country.create(name: "アルメニア", deleted: false)
Country.create(name: "アンゴラ", deleted: false)
Country.create(name: "アンティグア・バーブーダ", deleted: false)
Country.create(name: "アンドラ", deleted: false)
Country.create(name: "イエメン", deleted: false)
Country.create(name: "イギリス", deleted: false)
Country.create(name: "イスラエル", deleted: false)
Country.create(name: "イタリア", deleted: false)
Country.create(name: "イラク", deleted: false)
Country.create(name: "イラン", deleted: false)
Country.create(name: "インド", deleted: false)
Country.create(name: "インドネシア", deleted: false)
Country.create(name: "ウガンダ", deleted: false)
Country.create(name: "ウクライナ", deleted: false)
Country.create(name: "ウズベキスタン", deleted: false)
Country.create(name: "ウルグアイ", deleted: false)
Country.create(name: "エクアドル", deleted: false)
Country.create(name: "エジプト", deleted: false)
Country.create(name: "エストニア", deleted: false)
Country.create(name: "エチオピア", deleted: false)
Country.create(name: "エリトリア", deleted: false)
Country.create(name: "エルサルバドル", deleted: false)
Country.create(name: "沿ドニエストル", deleted: false)
Country.create(name: "オーストラリア", deleted: false)
Country.create(name: "オーストリア", deleted: false)
Country.create(name: "オマーン", deleted: false)
Country.create(name: "オランダ", deleted: false)
Country.create(name: "ガーナ", deleted: false)
Country.create(name: "カーボベルデ", deleted: false)
Country.create(name: "ガイアナ", deleted: false)
Country.create(name: "カザフスタン", deleted: false)
Country.create(name: "カタール", deleted: false)
Country.create(name: "カナダ", deleted: false)
Country.create(name: "ガボン", deleted: false)
Country.create(name: "カメルーン", deleted: false)
Country.create(name: "韓国", deleted: false)
Country.create(name: "ガンビア", deleted: false)
Country.create(name: "カンボジア", deleted: false)
Country.create(name: "北キプロス・トルコ共和国", deleted: false)
Country.create(name: "北朝鮮", deleted: false)
Country.create(name: "ギニア", deleted: false)
Country.create(name: "ギニアビサウ", deleted: false)
Country.create(name: "キプロス", deleted: false)
Country.create(name: "キューバ", deleted: false)
Country.create(name: "ギリシャ", deleted: false)
Country.create(name: "キリバス", deleted: false)
Country.create(name: "キルギス", deleted: false)
Country.create(name: "グアテマラ", deleted: false)
Country.create(name: "クウェート", deleted: false)
Country.create(name: "クック諸島", deleted: false)
Country.create(name: "グルジア", deleted: false)
Country.create(name: "グレナダ", deleted: false)
Country.create(name: "クロアチア", deleted: false)
Country.create(name: "ケニア", deleted: false)
Country.create(name: "コートジボワール", deleted: false)
Country.create(name: "コスタリカ", deleted: false)
Country.create(name: "コソボ", deleted: false)
Country.create(name: "コモロ", deleted: false)
Country.create(name: "コロンビア", deleted: false)
Country.create(name: "コンゴ共和国", deleted: false)
Country.create(name: "コンゴ民主共和国", deleted: false)
Country.create(name: "サウジアラビア", deleted: false)
Country.create(name: "サモア", deleted: false)
Country.create(name: "サントメ・プリンシペ", deleted: false)
Country.create(name: "ザンビア", deleted: false)
Country.create(name: "サンマリノ", deleted: false)
Country.create(name: "シエラレオネ", deleted: false)
Country.create(name: "ジブチ", deleted: false)
Country.create(name: "ジャマイカ", deleted: false)
Country.create(name: "シリア", deleted: false)
Country.create(name: "シンガポール", deleted: false)
Country.create(name: "ジンバブエ", deleted: false)
Country.create(name: "スイス", deleted: false)
Country.create(name: "スウェーデン", deleted: false)
Country.create(name: "スーダン", deleted: false)
Country.create(name: "スペイン", deleted: false)
Country.create(name: "スリナム", deleted: false)
Country.create(name: "スリランカ", deleted: false)
Country.create(name: "スロバキア", deleted: false)
Country.create(name: "スロベニア", deleted: false)
Country.create(name: "スワジランド", deleted: false)
Country.create(name: "セーシェル", deleted: false)
Country.create(name: "赤道ギニア", deleted: false)
Country.create(name: "セネガル", deleted: false)
Country.create(name: "セルビア", deleted: false)
Country.create(name: "セントクリストファー・ネイビス", deleted: false)
Country.create(name: "セントビンセント・グレナディーン", deleted: false)
Country.create(name: "セントルシア", deleted: false)
Country.create(name: "ソマリア", deleted: false)
Country.create(name: "ソマリランド", deleted: false)
Country.create(name: "ソロモン諸島", deleted: false)
Country.create(name: "タイ", deleted: false)
Country.create(name: "タジキスタン", deleted: false)
Country.create(name: "タンザニア", deleted: false)
Country.create(name: "チェコ", deleted: false)
Country.create(name: "チャド", deleted: false)
Country.create(name: "中央アフリカ", deleted: false)
Country.create(name: "中華人民共和国", deleted: false)
Country.create(name: "中華民国", deleted: false)
Country.create(name: "チュニジア", deleted: false)
Country.create(name: "チリ", deleted: false)
Country.create(name: "ツバル", deleted: false)
Country.create(name: "デンマーク", deleted: false)
Country.create(name: "ドイツ", deleted: false)
Country.create(name: "トーゴ", deleted: false)
Country.create(name: "ドミニカ共和国", deleted: false)
Country.create(name: "ドミニカ国", deleted: false)
Country.create(name: "トリニダード・トバゴ", deleted: false)
Country.create(name: "トルクメニスタン", deleted: false)
Country.create(name: "トルコ", deleted: false)
Country.create(name: "トンガ", deleted: false)
Country.create(name: "ナイジェリア", deleted: false)
Country.create(name: "ナウル", deleted: false)
Country.create(name: "ナゴルノ・カラバフ", deleted: false)
Country.create(name: "ナミビア", deleted: false)
Country.create(name: "ニウエ", deleted: false)
Country.create(name: "ニカラグア", deleted: false)
Country.create(name: "ニジェール", deleted: false)
Country.create(name: "西サハラ", deleted: false)
Country.create(name: "日本", deleted: false)
Country.create(name: "ニュージーランド", deleted: false)
Country.create(name: "ネパール", deleted: false)
Country.create(name: "ノルウェー", deleted: false)
Country.create(name: "バーレーン", deleted: false)
Country.create(name: "ハイチ", deleted: false)
Country.create(name: "パキスタン", deleted: false)
Country.create(name: "バチカン", deleted: false)
Country.create(name: "パナマ", deleted: false)
Country.create(name: "バヌアツ", deleted: false)
Country.create(name: "バハマ", deleted: false)
Country.create(name: "パプアニューギニア", deleted: false)
Country.create(name: "パラオ", deleted: false)
Country.create(name: "パラグアイ", deleted: false)
Country.create(name: "バルバドス", deleted: false)
Country.create(name: "パレスチナ", deleted: false)
Country.create(name: "ハンガリー", deleted: false)
Country.create(name: "バングラデシュ", deleted: false)
Country.create(name: "東ティモール", deleted: false)
Country.create(name: "フィジー", deleted: false)
Country.create(name: "フィリピン", deleted: false)
Country.create(name: "フィンランド", deleted: false)
Country.create(name: "ブータン", deleted: false)
Country.create(name: "ブラジル", deleted: false)
Country.create(name: "フランス", deleted: false)
Country.create(name: "ブルガリア", deleted: false)
Country.create(name: "ブルキナファソ", deleted: false)
Country.create(name: "ブルネイ", deleted: false)
Country.create(name: "ブルンジ", deleted: false)
Country.create(name: "ベトナム", deleted: false)
Country.create(name: "ベナン", deleted: false)
Country.create(name: "ベネズエラ", deleted: false)
Country.create(name: "ベラルーシ", deleted: false)
Country.create(name: "ベリーズ", deleted: false)
Country.create(name: "ペルー", deleted: false)
Country.create(name: "ベルギー", deleted: false)
Country.create(name: "ポーランド", deleted: false)
Country.create(name: "ボスニア・ヘルツェゴビナ", deleted: false)
Country.create(name: "ボツワナ", deleted: false)
Country.create(name: "ボリビア", deleted: false)
Country.create(name: "ポルトガル", deleted: false)
Country.create(name: "ホンジュラス", deleted: false)
Country.create(name: "マーシャル諸島", deleted: false)
Country.create(name: "マケドニア", deleted: false)
Country.create(name: "マダガスカル", deleted: false)
Country.create(name: "マラウイ", deleted: false)
Country.create(name: "マリ", deleted: false)
Country.create(name: "マルタ", deleted: false)
Country.create(name: "マレーシア", deleted: false)
Country.create(name: "ミクロネシア連邦", deleted: false)
Country.create(name: "南アフリカ共和国", deleted: false)
Country.create(name: "南オセチア", deleted: false)
Country.create(name: "南スーダン", deleted: false)
Country.create(name: "ミャンマー", deleted: false)
Country.create(name: "メキシコ", deleted: false)
Country.create(name: "モーリシャス", deleted: false)
Country.create(name: "モーリタニア", deleted: false)
Country.create(name: "モザンビーク", deleted: false)
Country.create(name: "モナコ", deleted: false)
Country.create(name: "モルディブ", deleted: false)
Country.create(name: "モルドバ", deleted: false)
Country.create(name: "モロッコ", deleted: false)
Country.create(name: "モンゴル", deleted: false)
Country.create(name: "モンテネグロ", deleted: false)
Country.create(name: "ヨルダン", deleted: false)
Country.create(name: "ラオス", deleted: false)
Country.create(name: "ラトビア", deleted: false)
Country.create(name: "リトアニア", deleted: false)
Country.create(name: "リビア", deleted: false)
Country.create(name: "リヒテンシュタイン", deleted: false)
Country.create(name: "リベリア", deleted: false)
Country.create(name: "ルーマニア", deleted: false)
Country.create(name: "ルクセンブルク", deleted: false)
Country.create(name: "ルワンダ", deleted: false)
Country.create(name: "レソト", deleted: false)
Country.create(name: "レバノン", deleted: false)
Country.create(name: "ロシア", deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE countries")

ActiveRecord::Base.connection.execute("TRUNCATE occupations")
ActiveRecord::Base.connection.reset_pk_sequence!("occupations")
Occupation.create(name: "会社役員", disp_seq: 1, deleted: false)
Occupation.create(name: "会社員", disp_seq: 2, deleted: false)
Occupation.create(name: "公務員", disp_seq: 3, deleted: false)
Occupation.create(name: "自営業", disp_seq: 4, deleted: false)
Occupation.create(name: "パート/アルバイト", disp_seq: 5, deleted: false)
Occupation.create(name: "主婦", disp_seq: 6, deleted: false)
Occupation.create(name: "学生", disp_seq: 7, deleted: false)
Occupation.create(name: "その他", disp_seq: 8, deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE occupations")

ActiveRecord::Base.connection.execute("TRUNCATE prefectures")
ActiveRecord::Base.connection.reset_pk_sequence!("prefectures")
Prefecture.create(name: "北海道", deleted: false)
Prefecture.create(name: "青森県", deleted: false)
Prefecture.create(name: "岩手県", deleted: false)
Prefecture.create(name: "宮城県", deleted: false)
Prefecture.create(name: "秋田県", deleted: false)
Prefecture.create(name: "山形県", deleted: false)
Prefecture.create(name: "福島県", deleted: false)
Prefecture.create(name: "茨城県", deleted: false)
Prefecture.create(name: "栃木県", deleted: false)
Prefecture.create(name: "群馬県", deleted: false)
Prefecture.create(name: "埼玉県", deleted: false)
Prefecture.create(name: "千葉県", deleted: false)
Prefecture.create(name: "東京都", deleted: false)
Prefecture.create(name: "神奈川県", deleted: false)
Prefecture.create(name: "新潟県", deleted: false)
Prefecture.create(name: "富山県", deleted: false)
Prefecture.create(name: "石川県", deleted: false)
Prefecture.create(name: "福井県", deleted: false)
Prefecture.create(name: "山梨県", deleted: false)
Prefecture.create(name: "長野県", deleted: false)
Prefecture.create(name: "岐阜県", deleted: false)
Prefecture.create(name: "静岡県", deleted: false)
Prefecture.create(name: "愛知県", deleted: false)
Prefecture.create(name: "三重県", deleted: false)
Prefecture.create(name: "滋賀県", deleted: false)
Prefecture.create(name: "京都府", deleted: false)
Prefecture.create(name: "大阪府", deleted: false)
Prefecture.create(name: "兵庫県", deleted: false)
Prefecture.create(name: "奈良県", deleted: false)
Prefecture.create(name: "和歌山県", deleted: false)
Prefecture.create(name: "鳥取県", deleted: false)
Prefecture.create(name: "島根県", deleted: false)
Prefecture.create(name: "岡山県", deleted: false)
Prefecture.create(name: "広島県", deleted: false)
Prefecture.create(name: "山口県", deleted: false)
Prefecture.create(name: "徳島県", deleted: false)
Prefecture.create(name: "香川県", deleted: false)
Prefecture.create(name: "愛媛県", deleted: false)
Prefecture.create(name: "高知県", deleted: false)
Prefecture.create(name: "福岡県", deleted: false)
Prefecture.create(name: "佐賀県", deleted: false)
Prefecture.create(name: "長崎県", deleted: false)
Prefecture.create(name: "熊本県", deleted: false)
Prefecture.create(name: "大分県", deleted: false)
Prefecture.create(name: "宮崎県", deleted: false)
Prefecture.create(name: "鹿児島県", deleted: false)
Prefecture.create(name: "沖縄県", deleted: false)
Prefecture.create(name: "日本国外", deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE prefectures")

ActiveRecord::Base.connection.execute("TRUNCATE terms_of_services")
ActiveRecord::Base.connection.reset_pk_sequence!("terms_of_services")
TermsOfService.create(content: TermsOfService001::CONTENT, deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE terms_of_services")

ActiveRecord::Base.connection.execute("TRUNCATE privacy_policies")
ActiveRecord::Base.connection.reset_pk_sequence!("privacy_policies")
PrivacyPolicy.create(content: PrivacyPolicy001::CONTENT, deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE privacy_policies")

ActiveRecord::Base.connection.execute("TRUNCATE courses")
ActiveRecord::Base.connection.reset_pk_sequence!("courses")
Course.create(name: "日常会話で学ぶ英語の基礎", description: "日常会話で使用されるフレーズを学びながら、発音、文法、単語、熟語などの英語の基礎を習得することができます。

英語の初心者の方や、英語を基礎から勉強し直したいと考えている方におすすめのレッスンです。", youtube_src: "http://www.youtube.com/embed/yPnCT8_8jOw?rel=0", cloudinary_public_id: "course1_001", deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE courses")

ActiveRecord::Base.connection.execute("TRUNCATE lessons")
ActiveRecord::Base.connection.reset_pk_sequence!("lessons")
Lesson.create(course_id: 1, number: 1, name: "挨拶1：友人と会った場合", price: 0, cloudinary_public_id: "course1_lesson1_main_001", description: "友人と挨拶を交わすときに使用するフレーズを学習します。", is_released: true, scheduled_release_date: nil, release_date: Date::new(2012, 11, 28), panda_video_id: "2922972a0bface298abc0e630fd60f78", is_main_lesson: true, main_lesson_id: nil, deleted: false)
ActiveRecord::Base.connection.execute("VACUUM ANALYZE lessons")

Rails.cache.clear
